version: "3.9"

services:
  ev-homes-backend:
    build: .
    # image: ev_home-backend:1.0
    container_name: ev_homes_backend
    restart: unless-stopped

    network_mode: host # ⭐ THIS IS THE FIX

    env_file:
      - .env

    environment:
      NODE_OPTIONS: "--max-old-space-size=1536"

    volumes:
      - /var/www/storage:/app/storage

    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2024M

    security_opt:
      - no-new-privileges:true

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8082/health"]
      interval: 60s
      timeout: 10s
      retries: 3
