services:
  ev-homes-backend:
    build: .
    container_name: ev_homes_backend
    restart: unless-stopped

    # for linux
    network_mode: host
    # only for windows
    # ports:
    # - "8082:8082"

    env_file:
      - .env

    environment:
      TZ: Asia/Kolkata
      NODE_OPTIONS: "--max-old-space-size=2500"

    mem_limit: 4024m
    cpus: "2.0"

    volumes:
      - /var/www/storage:/app/storage

    security_opt:
      - no-new-privileges:true

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8082/health"]
      interval: 60s
      timeout: 10s
      retries: 3
